export { default as GeneralInput } from '@components/general/GeneralInput'
export { default as GeneralInputText } from '@components/general/GeneralInputText'
export { default as GeneralButton } from '@components/general/GeneralButton'
export { default as GeneralSearchContact } from '@components/general/GeneralSearchContact'
export { default as GeneralAvatar } from '@components/general/GeneralAvatar'
